In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [3]:
df = pd.read_csv(r"D:\donwloads\housing.csv",
                    sep=',', encoding='iso-8859-1')

#  Número de linhas e colunas
display('Número de linhas e colunas')
display(df.shape)

df.rename(columns={
    'RM': 'media_comodos',
    'LSTAT': 'percentual_classe_baixa',
    'PTRATIO': 'razao_aluno_professor',
    'MEDV': 'valor_medio_casas'
}, inplace=True)

display(df)

'Número de linhas e colunas'

(489, 4)

,media_comodos,percentual_classe_baixa,razao_aluno_professor,valor_medio_casas
0,6.575,4.98,15.3,504000.0
1,6.421,9.14,17.8,453600.0
2,7.185,4.03,17.8,728700.0
3,6.998,2.94,18.7,701400.0
4,7.147,5.33,18.7,760200.0
...,...,...,...,...
484,6.593,9.67,21.0,470400.0
485,6.120,9.08,21.0,432600.0
486,6.976,5.64,21.0,501900.0
487,6.794,6.48,21.0,462000.0


In [ ]:
# Invés de fazer todas as regressão existente, vamos juntas as 3 primeiras colunas e montar uma regressão delas

independente  = df.iloc[:, 0:3].values
independente

dependente = df.iloc[:, 3].values

In [20]:
x_treino, x_teste, y_treino, y_teste = train_test_split(independente, dependente, test_size=0.3, random_state=0)

In [21]:
multipla = LinearRegression()
multipla.fit(x_treino, y_treino)

LinearRegression()

In [22]:
multipla.intercept_
multipla.coef_

array([ 85325.36412937, -10775.41479323, -20133.58779106])

In [23]:
multipla.score(x_treino, y_treino)

0.7343049403294957

In [25]:
previsao = multipla.predict(x_teste)
previsao

array([418504.52251533, 682498.59311161, 310842.03220354, 399602.67212048,
       529013.04970446, 364349.16756502, 241564.07559959, 413075.10184459,
       476051.89023052, 371925.92192458, 324382.18849665, 357068.87403347,
       472650.96518839,  52625.76046357, 486476.7874084 , 312653.08514703,
       465067.60969605, 614663.51972717, 383059.21254559, 653229.85415898,
       677008.34036381, 653364.33988067,  15201.46316315, 452877.56192735,
       360692.75896586, 754677.40725013, 714803.22773315, 754640.19558449,
       430756.93101727, 422579.57707332, 378309.3992427 , 461958.22362764,
       472103.18520444, 681780.56381622, 457070.41410848, 769207.31373834,
       520822.33816699, 261675.315203  , 503180.52774604, 590132.54786611,
       324624.03541901, 452521.53520288, 400704.94316867, 498314.39406844,
       280336.01343561, 365481.99718596, 525798.46427921, 361547.63013434,
       716795.14226269, 407424.79029782, 679886.98036124, 445827.68346551,
       614892.98134094, 3

In [26]:
multipla.score(x_teste, y_teste)

0.6817814124380092

In [28]:
valor_casa = multipla.predict([[8, 25, 15]])
valor_casa

array([546003.18143388])